#!/bin/sh

APPDIR=$(dirname "$0")
java  -Djava.library.path="$APPDIR" -cp "$APPDIR/lib/TheSnake.jar:$APPDIR/lib/core.jar:$APPDIR/lib/PeasyCam.jar:$APPDIR/lib/guicomponents.jar:$APPDIR/lib/opengl.jar:$APPDIR/lib/jogl.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/opengl.jar:$APPDIR/lib/jogl.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/oscP5.jar:$APPDIR/lib/oscP5.jar" TheSnake
